apiVersion: v1
kind: Secret
metadata:
  name: superset
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: superset
  url: https://apache.github.io/superset
  type: helm
